### ISSUE TITLE
[Client] Signup Page

### ISSUE THREAD

**Issue by k-lombard** [k-lombard/TutorCare#2]
Create frontend signup components that is in line with our figma design

**Comment by christophrrb** [comment]
Suggestion for issues:
- If it's [Client], acceptance criteria should be that the layout is in place (or in other words, no more can be done on the front-end programming until the back-end is implemented).
- If it's [API], acceptance criteria should be that the back-end implementation is complete and waiting for implementation of it on the front-end.
- Use a third label called like [Merge], [Integrate], or something like that for issues where the task is to merge the front- and back-end are being merged together.

This way, we can know more exactly what needs to be done for like sign up, login, etc., and this will help us to move issues through on the board more easily and prevent something like "I can't get this this text field centered, so the issue can't be completed" since that would just be a problem for [Client]—not [API].

This might have already been the thought process, but I at least wanted to explicitly say it to make sure we all are in accordance for how we want to do acceptance criteria for issues, but if you foresee any problems with doing it this way or have any objections, just send a reply.

With that being said, I think this story can be moved into the "Review in progress" column, so edits and suggestions to the sign up page can be made.

Current Layout
![image](https://user-images.githubusercontent.com/8262882/147965407-3ec335b5-f3be-4993-8dee-7525e2937a48.png)
